---
title: "Image Classification 1"
output: html_notebook
---

Courtesy of https://shirinsplayground.netlify.com/2018/06/keras_fruits/
Data from https://www.kaggle.com/moltean/fruits/data


```{r}
#Packages
library(keras) 
# may need to update package reticluate to make this work.  Currently only the development version of reticulate is sufficient so run 
##devtools::install_github("rstudio/reticulate")
#if that fails to to www.github.com/rstudio/reticulate, click on Clone > Download zip; back in RStudio go Tools > Install Packages > Install From select Package Archive File, browse to downloads and select the zip file you selected, click ok.  

```


```{r}
#Define Variables

# list of fruits to modle
fruit_list <- c("Kiwi", "Banana", "Apricot", "Avocado", "Cocos", "Clementine", "Mandarine", 
                "Orange", "Limes", "Lemon", "Peach", "Plum", "Raspberry", "Strawberry", 
                "Pineapple", "Pomegranate")

# number of output classes (i.e. fruits)
output_n <- length(fruit_list)

# image size to scale down to (original images are 100 x 100 px)
img_width <- 20
img_height <- 20
target_size <- c(img_width, img_height)

# RGB = 3 channels
channels <- 3

# path to image folders
train_image_files_path <- "../data/input_data/fruits-360/Training/"
valid_image_files_path <- "../data/input_data/fruits-360/Validation/"
```



```{r}
#Define image augmentation

# optional data augmentation
train_data_gen = image_data_generator(
  rescale = 1/255 #,
  #rotation_range = 40,
  #width_shift_range = 0.2,
  #height_shift_range = 0.2,
  #shear_range = 0.2,
  #zoom_range = 0.2,
  #horizontal_flip = TRUE,
  #fill_mode = "nearest"
)

# Validation data shouldn't be augmented! But it should also be scaled.
valid_data_gen <- image_data_generator(
  rescale = 1/255
  )  


```


```{r}
#Load images

# training images
train_image_array_gen <- flow_images_from_directory(train_image_files_path, 
                                          train_data_gen,
                                          target_size = target_size,
                                          class_mode = "categorical",
                                          classes = fruit_list,
                                          seed = 42)

# validation images
valid_image_array_gen <- flow_images_from_directory(valid_image_files_path, 
                                          valid_data_gen,
                                          target_size = target_size,
                                          class_mode = "categorical",
                                          classes = fruit_list,
                                          seed = 42)

cat("Number of images per class:")
table(factor(train_image_array_gen$classes))

cat("\nClass label vs index mapping:\n")
train_image_array_gen$class_indices

fruits_classes_indices <- train_image_array_gen$class_indices
save(fruits_classes_indices, file = "/Users/shiringlander/Documents/Github/DL_AI/Tutti_Frutti/fruits-360/fruits_classes_indices.RData")


```


